name: .NET CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build -c Release --no-restore

      - name: Run tests
        run: dotnet test -c Release --no-build

      - name: Publish project
        run: dotnet publish -c Release --no-build -o ./publish

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: "bmiA00082440Hardeep"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
